# Generated by Django 3.1.6 on 2021-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommingSoonWatches',
        ),
    ]
