# Generated by Django 3.1.6 on 2021-04-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_delete_commingsoonwatches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addsuggestedproducts',
            old_name='file',
            new_name='image',
        ),
    ]
