# Generated by Django 3.1.6 on 2021-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrowatchshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamrowatchshop',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hamrowatchshop',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
