# Generated by Django 3.1.6 on 2021-04-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamrowatchshop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='full_name',
        ),
    ]
