# Generated by Django 3.1.6 on 2021-04-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamrowatchshop', '0007_auto_20210417_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comingsoonwatch',
            name='name',
        ),
    ]
