# Generated by Django 3.1.6 on 2021-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrowatchshop', '0008_remove_comingsoonwatch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='menWatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='static/uploads')),
            ],
        ),
    ]
