# Generated by Django 3.1.6 on 2021-04-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hamrowatchshop', '0010_kidswatches_onsalewatches_womenwatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('totalprice', models.FloatField(default=0)),
                ('ShadeProducts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hamrowatchshop.hamrowatchshop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
