# Generated by Django 3.1.6 on 2021-04-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamrowatchshop', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ShadeProducts',
            new_name='HamroWatchShop',
        ),
    ]
