# Generated by Django 3.1.6 on 2021-09-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamrowatchshop', '0012_auto_20210419_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComingSoonWatch',
            new_name='ComingSoonProduct',
        ),
        migrations.RenameModel(
            old_name='HamroWatchShop',
            new_name='HamroShopCenter',
        ),
        migrations.RenameModel(
            old_name='onsaleWatches',
            new_name='kidsClothes',
        ),
        migrations.RenameModel(
            old_name='menWatches',
            new_name='menClothes',
        ),
        migrations.RenameModel(
            old_name='kidsWatches',
            new_name='onsaleClothes',
        ),
        migrations.RenameModel(
            old_name='womenWatches',
            new_name='womenClothes',
        ),
    ]
