# Generated by Django 3.1.6 on 2021-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrowatchshop', '0013_auto_20210901_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='totalprice',
            field=models.FloatField(),
        ),
    ]
